# Generated by Django 4.2.7 on 2023-12-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hi', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
