# Generated by Django 4.2.7 on 2023-12-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hi', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
